export const permissions = [
  'user:list',
  'user:read',
  'user:create',
  'user:update',
  'user:delete',
  'role:list',
  'role:read',
  'role:create',
  'role:update',
  'role:delete',
  'permission:list',
  'setting:list',
  'setting:update',
  'menu:list',
  'menu:create',
  'menu:update',
  'menu:delete',
  'dictionary:list',
  'dictionary:read',
  'dictionary:create',
  'dictionary:update',
  'dictionary:delete',
  'audit:list',
  'file:upload',
  'file:list',
  'file:delete',
  'session:list',
  'session:revoke',
  'dashboard:read',
  'generator:preview',
] as const;

export type PermissionKey = (typeof permissions)[number];

export const rolePermissions: Record<string, PermissionKey[]> = {
  admin: [...permissions],
  operator: [
    'user:list',
    'user:read',
    'role:list',
    'permission:list',
    'setting:list',
    'menu:list',
    'dictionary:list',
    'dictionary:read',
    'dictionary:create',
    'dictionary:update',
    'audit:list',
    'file:upload',
    'file:list',
    'session:list',
    'dashboard:read',
  ],
  viewer: [
    'user:list',
    'user:read',
    'role:list',
    'permission:list',
    'setting:list',
    'menu:list',
    'dictionary:list',
    'dictionary:read',
    'audit:list',
    'file:list',
    'session:list',
    'dashboard:read',
  ],
};

export const defaultRoles = [
  { key: 'admin', name: 'Administrator', description: 'Full system access' },
  { key: 'operator', name: 'Operator', description: 'Operational access without destructive administration' },
  { key: 'viewer', name: 'Viewer', description: 'Read-only access' },
] as const;
